export const SIGNEDIN = 'SIGNEDIN'
export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const CONFIRM_SIGNUP = 'CONFIRM_SIGNUP'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
